name: Regression manual trigger

on:
  workflow_dispatch:

env:
    SECRET_VARIABLE1: ${{ secrets.ABC }}
    VAR: ${{ vars.VAR }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Write Secrets to Properties File
      run: |
        echo "" >> src/test/azure.properties    
        echo "AZURE_CLIENT_ID=xyz" >> src/test/azure.properties
        echo "AZURE_CLIENT_SECRET=xyz" >> src/test/azure.properties
        echo "" >> src/test/azure-Desp.properties 
        echo "AZURE_CLIENT_ID=xyz" >> src/test/azure-Desp.properties
        echo "AZURE_CLIENT_SECRET=xyz" >> src/test/azure-Desp.properties
    - name: Move files to shared workspace
      run: |
        cp src/test/azure.properties $GITHUB_WORKSPACE/azure.properties
        cp src/test/azure-Desp.properties $GITHUB_WORKSPACE/azure-Desp.properties  
        ls -l $GITHUB_WORKSPACE

    - name: Create properties files
      run: |
          mkdir -p folder1
          echo "MY_SECRET_KEY_1=xyz" > folder1/file1.properties
          echo "MY_SECRET_KEY_2=abc" > folder1/file2.properties

    - name: Save properties files to cache
      uses: actions/cache@v3
      with:
          path: folder1
          key: ${{ runner.os }}-properties-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-properties-

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11  # Adjust to your JDK version

    # - name: Replace Variables in Properties File
    #   run: |
    #     sed -i "s|{{SECRET_VARIABLE1}}|$SECRET_VARIABLE1g" src/test/file.properties
    #     sed -i "s|{{SECRET_VARIABLE1}}|$VAR|g" src/test/file.properties
        
    #     # Add more sed commands for each variable you want to replace

    - name: Use Properties File
      run: |
        # Use your properties file in your build or deployment process
  job2:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # - name: Move properties files into an existing folder
    #   run: |
    #       ls -l $GITHUB_WORKSPACE
    #       cp $GITHUB_WORKSPACE/azure.properties src/test/azure.properties
    #       cp $GITHUB_WORKSPACE/azure-Desp.properties src/test/azure-Desp.properties
    - name: Restore properties files from cache
      uses: actions/cache@v3
      with:
          path: folder1
          key: ${{ runner.os }}-properties-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-properties-

    - name: Verify cached files
      run: |
          ls -l folder1
          cat folder1/file1.properties
          cat folder1/file2.properties

    - name: Move files to the desired directory
      run: |
          cp folder1/file1.properties src/test/
          cp folder1/file2.properties src/test/

